### PR TITLE
Debian add build deps

### PR DESCRIPTION
**Pull request by intrigeri**
Without these changes I can't build fw-daemon in a clean pbuilder chroot. Not sure how you do it usually, but whatever :)

### CODE REVIEW

**Comment by brl** [comment]
I keep all of the packaging in the branch 'debian' instead of master.  If you check out the branch debian and add those build-dependencies it should work.

**Comment by brl** [comment]
To be more clear, maybe you wanted me to merge the build-dependencies change into branch debian rather than merge all the packaging into branch master.

**Comment by intrigeri** [comment]
Bruce Leidl:

> To be more clear, maybe you wanted me to merge the build-dependencies change into branch debian rather than merge all the packaging into branch master.

Yes, exactly. Sorry I got it wrong, I'm not used to GitHub.

**Comment by intrigeri** [comment]
> I keep all of the packaging in the branch 'debian' instead of master.  If you check out the branch debian and add those build-dependencies it should work.

Yes, my branch is based on your `debian` branch.

**Comment by brl** [comment]
Ok great there was an easy option for me to fix this.

**Comment by xSmurf** [comment]
Fixes #15

**Pull request merged**
